export const metiersIT = [
  "Développeur Frontend",
  "Développeur Backend",
  "Développeur Fullstack",
  "Développeur React",
  "Développeur Angular",
  "Développeur Vue.js",
  "Développeur Node.js",
  "Développeur Python",
  "Développeur Java",
  "Développeur C#",
  "Développeur PHP",
  "Développeur Ruby",
  "Développeur mobile iOS",
  "Développeur mobile Android",
  "Développeur Flutter",
  "Développeur React Native",
  "DevOps",
  "Ingénieur Cloud",
  "Architecte Cloud",
  "SysAdmin",
  "Ingénieur Réseaux",
  "Administrateur Systèmes",
  "Administrateur Réseaux",
  "Consultant IT",
  "Consultant Cloud",
  "Consultant Sécurité",
  "Expert Cybersécurité",
  "Analyste sécurité",
  "Penetration Tester",
  "Data Scientist",
  "Data Analyst",
  "Data Engineer",
  "Ingénieur Machine Learning",
  "Ingénieur IA",
  "Architecte Data",
  "Administrateur Base de données",
  "DBA SQL",
  "DBA NoSQL",
  "Business Analyst IT",
  "Chef de projet IT",
  "Product Owner",
  "Scrum Master",
  "UX Designer",
  "UI Designer",
  "Designer UI/UX",
  "QA Engineer",
  "Testeur QA",
  "Ingénieur Test Logiciel",
  "Automation Test Engineer",
  "SRE (Site Reliability Engineer)",
  "Technical Support Level 1",
  "Technical Support Level 2",
  "Ingénieur Support",
  "Analyste Fonctionnel",
  "Analyste Technique",
  "Intégrateur Web",
  "Intégrateur Frontend",
  "Intégrateur Backend",
  "Développeur ERP",
  "Développeur CRM",
  "Développeur Salesforce",
  "Développeur SAP",
  "Développeur Magento",
  "Développeur Prestashop",
  "Développeur WordPress",
  "Développeur Joomla",
  "Développeur Drupal",
  "Dev Fullstack JavaScript",
  "Dev Fullstack Python",
  "Dev Fullstack Java",
  "Dev Fullstack PHP",
  "Ingénieur Big Data",
  "Ingénieur ETL",
  "Ingénieur Data Pipeline",
  "Ingénieur Infrastructure",
  "Administrateur Serveur",
  "Ingénieur Virtualisation",
  "Ingénieur Docker",
  "Ingénieur Kubernetes",
  "Ingénieur Réseaux Sécurisés",
  "Ingénieur Télécom",
  "Consultant ERP",
  "Consultant CRM",
  "Développeur Blockchain",
  "Développeur Solidity",
  "Développeur NFT",
  "Ingénieur IoT",
  "Ingénieur Embedded",
  "Ingénieur Système Embarqué",
  "DevOps Cloud",
  "Architecte DevOps",
  "Ingénieur Automation",
  "Ingénieur Infrastructure Cloud",
  "Consultant IT Junior",
  "Consultant IT Senior",
  "Développeur API",
  "Développeur GraphQL",
  "Développeur REST",
  "Développeur Microservices",
  "DevOps Sécurité",
  "Analyste Sécurité IT",
  "Cloud Security Engineer"
];
